runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css  

- url: /images
  static_dir: images

- url: /(.*\.(gif|png|jpg|ico))
  static_files: images/\1
  upload: static/(.*\.(gif|png|jpg|ico))
  
- url: /.*
  script: pm_tools.application
